INCLUDE Irvine32.inc
;Integrantes Del Equipo
;Gonzalez Saldivar Luis Roberto
;Martinez Reyes Fernando
.data
; Área de Declaración de Variables

NTRAJES_8 DB "CUANTOS TRAJES DESEA ADQUIRIR", 0
MPRECIOS_8 DB "INGRESE EL COSTO DEL TRAJE", 0
PARCIAL_8 DB "EL PRECIO APLICADO CON DESCUENTO ES", 0
TOTAL_8 DB "EL PRECIO FINAL ES: ", 0
RES_8 DWORD 0
DESC1_B DWORD 250
DESC2_8 DWORD 100

.code
     main PROC
          ;lógica del Programa

          ;ALMACENES ""EL HARAPIENTO DISTINGUIDO" TIENE UNA PROMOCIÓN: A TODOS LOS TRAJES QUE TIENE UN PRECIO SUPERIOR
          ;A 2500 SE LES APLICA UN DESCUENTO DE 250 PESOS, A TODOS LOS DEMAS SE LES APLICA SOLO 100 PESOS, REALICE UN 
          ;PROGRAMA PARA DETRMINAR EL PRECIO FINAL QUE SE DEBE PAGAR UNA PERSONA POR COMPRAR N TRAJES DE M PRECIOS
          ;Y CUANTO ES EL DESCUENTO TOTAL Y PARCIAL SE LE OBTENDRÁ

          MOV EDX, OFFSET NTRAJES_8
          CALL WRITESTRING
          CALL CRLF
          CALL READINT 
          CALL CRLF
          MOV ECX, EAX
          MOV EBX, 1 ;CONTADOR DE TRAJES
          
          CICLO:
            CALL CRLF
            MOV EDX, OFFSET MPRECIOS_8
            CALL WRITESTRING
            MOV EAX, EBX
            CALL WIRTEDEC
            CALL CRLF
            ADD EBX, 1
            CALL REDINT
            CALL CRLF
            CMP EAX, 2500



          exit
     main ENDP
     END main